sudo: false
services:
- docker
language: bash
script:
- docker build -t ansi/feelflight-11-1-asset:latest .
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker push ansi/feelflight-11-1-asset:latest
